component: nuxtjs # (必填) 组件名称，此处为 nuxtjs
name: serverless-tool # (必填) 实例名称
org:  # (可选) 用于记录组织信息，默认值为您的腾讯云账户 APPID
app: serverless-tool # (可选) 该 nuxt.js 项目名称
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs12.16
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
    environment: release